//! Atmospheric turbulence: von Kármán phase screens and turbulent paths (M3).
//!
//! Screens are generated by the standard FFT method — complex Gaussian noise
//! filtered by the square root of the phase power spectral density — with
//! three levels of subharmonic low-frequency compensation (Lane et al. 1992),
//! without which the FFT grid under-represents the large eddies that dominate
//! beam wander and the structure function at large separations.
//!
//! Spectrum (κ in rad/m): the von Kármán phase PSD
//!
//! ```text
//! Φ_φ(κ) = 0.49 · r0^(-5/3) · (κ² + κ0²)^(-11/6),   κ0 = 2π/L0
//! ```
//!
//! which reduces to the Kolmogorov `0.49 r0^(-5/3) κ^(-11/3)` for scales well
//! inside the outer scale `L0`. The Fried parameter `r0` of a slab of
//! thickness `dz` with structure constant `Cn²` is
//! `r0 = (0.423 k² Cn² dz)^(-3/5)` (plane wave).
//!
//! Reproducibility contract (T4): every random draw comes from a caller-held
//! `ChaCha12Rng`; Monte-Carlo realizations use `set_stream(i)` on a
//! master-seeded generator, so realization `i` is identical regardless of
//! thread count or scheduling.

use ndarray::Array2;
use ndrustfft::{FftHandler, ndifft};
use num_complex::Complex64;
use rand::{Rng, RngExt};
use rand_distr::StandardNormal;
use std::f64::consts::PI;

use crate::grid::Grid;
use crate::medium::Medium;
use crate::validate::fried_r0;

/// Kolmogorov/von Kármán phase-PSD coefficient: `0.023·(2π)^(5/3)`.
const PSD_COEFF: f64 = 0.4896;
/// Subharmonic compensation depth: each level refines Δκ by 3×.
const SUBHARMONIC_LEVELS: u32 = 6;

/// Von Kármán phase PSD `Φ_φ(κ)` (rad²·m²) at transverse frequency κ (rad/m).
fn phase_psd(kappa_sq: f64, r0: f64, kappa0: f64) -> f64 {
    PSD_COEFF * r0.powf(-5.0 / 3.0) * (kappa_sq + kappa0 * kappa0).powf(-11.0 / 6.0)
}

/// Cell-averaged PSD: mean of `Φ_φ` over a 5×5 midpoint subgrid of the
/// frequency cell of side `dcell` centred on `(kx, ky)`.
///
/// The PSD is steep and convex (`κ^(-11/3)`), so its value at a cell centre
/// underestimates the cell's integrated power — by an order one factor in the
/// cells nearest the origin, which dominate the structure function at large
/// separations. Applied to the subharmonic modes, whose cells are exactly
/// those steep near-origin regions; the regular FFT cells keep the point
/// value (cell-averaging them was measured to overshoot the structure
/// function by as much as the naive recipe undershoots it, because the
/// `1 − cos(κ·r)` weighting in D suppresses the near-origin corner of a cell
/// that dominates its mean). This combination reproduces Kolmogorov D(r) to
/// ~5% over a decade of separations — the M3 gate pins it.
fn cell_mean_psd(kx: f64, ky: f64, dcell: f64, r0: f64, kappa0: f64) -> f64 {
    let mut sum = 0.0;
    for u in 0..5 {
        for v in 0..5 {
            let ox = (u as f64 - 2.0) / 5.0 * dcell;
            let oy = (v as f64 - 2.0) / 5.0 * dcell;
            let (kxs, kys) = (kx + ox, ky + oy);
            sum += phase_psd(kxs * kxs + kys * kys, r0, kappa0);
        }
    }
    sum / 25.0
}

/// Generator of von Kármán phase screens on a fixed grid, with the FFT plan
/// and scratch buffers built once and reused across screens and realizations.
pub struct ScreenGenerator {
    grid: Grid,
    r0: f64,
    kappa0: f64,
    subharmonics: bool,
    handler: FftHandler<f64>,
    scratch_a: Array2<Complex64>,
    scratch_b: Array2<Complex64>,
}

impl ScreenGenerator {
    /// Screens with Fried parameter `r0` (m) and outer scale `l0_outer` (m)
    /// on `grid`. `subharmonics` adds the low-frequency compensation — wanted
    /// for physical screens; disable it only when strict periodicity matters
    /// more than large-scale statistics (e.g. plane-wave scintillation runs).
    pub fn new(grid: Grid, r0: f64, l0_outer: f64, subharmonics: bool) -> Self {
        assert!(r0 > 0.0 && r0.is_finite(), "r0 must be positive, got {r0}");
        assert!(
            l0_outer > 0.0 && l0_outer.is_finite(),
            "outer scale must be positive and finite, got {l0_outer}"
        );
        let n = grid.n;
        Self {
            grid,
            r0,
            kappa0: 2.0 * PI / l0_outer,
            subharmonics,
            handler: FftHandler::new(n),
            scratch_a: Array2::zeros((n, n)),
            scratch_b: Array2::zeros((n, n)),
        }
    }

    /// Draw one phase screen (radians), zero-mean.
    ///
    /// Synthesis: `φ = N²·Re(IFFT(a))` with `a(κ) = (g₁ + i·g₂)·√Φ_φ(κ)·Δκ`
    /// and independent standard normals `g₁, g₂` — giving each Fourier mode
    /// the variance `Φ_φ(κ)·Δκ²` the continuous spectrum prescribes. Draws
    /// happen in fixed row-major order, so a given RNG state maps to exactly
    /// one screen.
    pub fn generate(&mut self, rng: &mut impl Rng) -> Array2<f64> {
        let n = self.grid.n;
        let dk = 2.0 * PI / self.grid.extent();
        let mut a: Array2<Complex64> = Array2::zeros((n, n));
        for iy in 0..n {
            for ix in 0..n {
                if ix == 0 && iy == 0 {
                    continue; // piston: handled by the subharmonic levels
                }
                let kx = dk * signed_index(ix, n);
                let ky = dk * signed_index(iy, n);
                let amp = phase_psd(kx * kx + ky * ky, self.r0, self.kappa0).sqrt() * dk;
                let g1: f64 = rng.sample(StandardNormal);
                let g2: f64 = rng.sample(StandardNormal);
                a[[iy, ix]] = Complex64::new(g1 * amp, g2 * amp);
            }
        }
        ndifft(&a, &mut self.scratch_a, &self.handler, 0);
        ndifft(&self.scratch_a, &mut self.scratch_b, &self.handler, 1);
        let n2 = (n * n) as f64;
        let mut screen = self.scratch_b.mapv(|c| c.re * n2);

        if self.subharmonics {
            self.add_subharmonics(&mut screen, rng);
        }

        let mean = screen.sum() / n2;
        screen.mapv_inplace(|p| p - mean);
        screen
    }

    /// Lane-style subharmonics: `SUBHARMONIC_LEVELS` refinements of the
    /// central (excluded) frequency cell, each a 3×3 grid of modes at spacing
    /// `Δκ/3^p` with its own centre excluded (the next level covers it).
    fn add_subharmonics(&self, screen: &mut Array2<f64>, rng: &mut impl Rng) {
        let n = self.grid.n;
        let dk = 2.0 * PI / self.grid.extent();
        for p in 1..=SUBHARMONIC_LEVELS {
            let dkp = dk / 3f64.powi(p as i32);
            for jy in -1i32..=1 {
                for jx in -1i32..=1 {
                    if jx == 0 && jy == 0 {
                        continue;
                    }
                    let kx = jx as f64 * dkp;
                    let ky = jy as f64 * dkp;
                    let amp = cell_mean_psd(kx, ky, dkp, self.r0, self.kappa0).sqrt() * dkp;
                    let g1: f64 = rng.sample(StandardNormal);
                    let g2: f64 = rng.sample(StandardNormal);
                    let a = Complex64::new(g1 * amp, g2 * amp);
                    // Separable direct synthesis on the same x = l·dx
                    // convention the FFT part uses.
                    let ex: Vec<Complex64> = (0..n)
                        .map(|l| Complex64::from_polar(1.0, kx * l as f64 * self.grid.dx))
                        .collect();
                    let ey: Vec<Complex64> = (0..n)
                        .map(|m| Complex64::from_polar(1.0, ky * m as f64 * self.grid.dx))
                        .collect();
                    for (m, row) in screen.rows_mut().into_iter().enumerate() {
                        let aey = a * ey[m];
                        for (l, v) in row.into_iter().enumerate() {
                            *v += (aey * ex[l]).re;
                        }
                    }
                }
            }
        }
    }
}

/// FFT-ordered signed index: `i` for `i ≤ n/2`, wrapped negative beyond.
fn signed_index(i: usize, n: usize) -> f64 {
    if i <= n / 2 {
        i as f64
    } else {
        i as f64 - n as f64
    }
}

/// A turbulent propagation path: one phase screen per z-slab, exposed to the
/// propagator through the `Medium` trait (`δn = φ/(k·dz)`, so the slab phase
/// `k·δn·dz` the propagator applies is exactly the screen phase `φ`).
pub struct TurbulentPath {
    screens: Vec<Array2<f64>>,
    k: f64,
    dz: f64,
    /// Diffraction-only sub-slabs per screen; the screen phase is applied in
    /// full at the central sub-slab. 1 = one slab per screen (the default).
    substeps: usize,
}

impl TurbulentPath {
    /// A path of `n_screens` slabs covering `z_total` (m) with uniform
    /// structure constant `cn2` (m^(-2/3)) and outer scale `l0_outer` (m).
    ///
    /// Realization `realization` of master seed `master_seed`: the ChaCha
    /// stream is set per realization, so ensembles are reproducible and
    /// thread-order independent (T4).
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        grid: Grid,
        wavelength: f64,
        cn2: f64,
        l0_outer: f64,
        z_total: f64,
        n_screens: usize,
        master_seed: u64,
        realization: u64,
    ) -> Self {
        use rand::SeedableRng;
        assert!(n_screens > 0, "need at least one screen");
        let dz = z_total / n_screens as f64;
        let r0_slab = fried_r0(cn2, wavelength, dz);
        let mut generator = ScreenGenerator::new(grid, r0_slab, l0_outer, true);
        let mut rng = rand_chacha::ChaCha12Rng::seed_from_u64(master_seed);
        rng.set_stream(realization);
        let screens = (0..n_screens)
            .map(|_| generator.generate(&mut rng))
            .collect();
        Self::from_screens(screens, wavelength, dz)
    }

    /// Wrap pre-generated phase screens (radians), one per slab of thickness
    /// `dz`, into a `Medium`.
    pub fn from_screens(screens: Vec<Array2<f64>>, wavelength: f64, dz: f64) -> Self {
        assert!(!screens.is_empty(), "need at least one screen");
        Self {
            screens,
            k: 2.0 * PI / wavelength,
            dz,
            substeps: 1,
        }
    }

    /// Subdivide each screen slab into `substeps` diffraction-only sub-slabs,
    /// with the full screen phase applied at the central one. The physics is
    /// unchanged (each screen still imposes its phase exactly once); the extra
    /// steps only refine where along z the field is observable — e.g. for a
    /// smooth side-view rendering. `substeps = 1` is the identity.
    pub fn with_substeps(mut self, substeps: usize) -> Self {
        assert!(substeps > 0, "need at least one substep per screen");
        self.substeps = substeps;
        self
    }

    /// Number of screens on this path.
    pub fn n_screens(&self) -> usize {
        self.screens.len()
    }

    /// Total number of propagation slabs (screens × substeps).
    pub fn n_slabs(&self) -> usize {
        self.screens.len() * self.substeps
    }

    /// Propagation slab thickness (m): screen spacing / substeps.
    pub fn dz(&self) -> f64 {
        self.dz / self.substeps as f64
    }
}

impl Medium for TurbulentPath {
    fn index_perturbation(&self, z_slab: usize) -> Array2<f64> {
        let screen = self.screens.get(z_slab / self.substeps).unwrap_or_else(|| {
            panic!(
                "slab {z_slab} beyond path of {} screens x {} substeps",
                self.screens.len(),
                self.substeps
            )
        });
        if z_slab % self.substeps != self.substeps / 2 {
            // Diffraction-only sub-slab: no medium perturbation.
            return Array2::zeros(screen.dim());
        }
        let scale = 1.0 / (self.k * self.dz());
        screen.mapv(|phi| phi * scale)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;
    use rand_chacha::ChaCha12Rng;

    #[test]
    fn screen_is_zero_mean_and_reproducible() {
        let grid = Grid::new(64, 0.05);
        let mut generator = ScreenGenerator::new(grid, 0.2, 10.0, true);
        let mut rng = ChaCha12Rng::seed_from_u64(42);
        let s1 = generator.generate(&mut rng);
        assert!(
            s1.sum().abs() / (64.0 * 64.0) < 1e-12,
            "screen not zero-mean"
        );

        // Same seed → bitwise identical screen.
        let mut rng2 = ChaCha12Rng::seed_from_u64(42);
        let s2 = generator.generate(&mut rng2);
        assert_eq!(s1, s2);
    }

    #[test]
    fn different_streams_give_different_screens() {
        let grid = Grid::new(32, 0.05);
        let mut generator = ScreenGenerator::new(grid, 0.2, 10.0, false);
        let mut rng_a = ChaCha12Rng::seed_from_u64(7);
        rng_a.set_stream(0);
        let mut rng_b = ChaCha12Rng::seed_from_u64(7);
        rng_b.set_stream(1);
        let sa = generator.generate(&mut rng_a);
        let sb = generator.generate(&mut rng_b);
        assert!(sa != sb, "distinct streams produced identical screens");
    }

    /// Ensemble phase variance vs the analytic von Kármán total
    /// `σ² ≈ 0.0863·(L0/r0)^(5/3)` — a scaling check on the PSD
    /// normalization that is independent of the structure-function gate.
    #[test]
    fn screen_variance_matches_von_karman_total() {
        let grid = Grid::new(128, 0.05); // extent 6.4 m
        let (r0, l0): (f64, f64) = (0.2, 3.0); // L0 well inside the grid
        let sigma2_ref = 0.0863 * (l0 / r0).powf(5.0 / 3.0);

        let mut generator = ScreenGenerator::new(grid, r0, l0, true);
        let mut rng = ChaCha12Rng::seed_from_u64(1);
        let n_screens = 60;
        let mut var_sum = 0.0;
        for _ in 0..n_screens {
            let s = generator.generate(&mut rng);
            var_sum += s.mapv(|p| p * p).sum() / (s.len() as f64);
        }
        let var = var_sum / n_screens as f64;
        let rel = (var - sigma2_ref).abs() / sigma2_ref;
        assert!(
            rel < 0.15,
            "screen variance {var:.3} vs von Kármán {sigma2_ref:.3} ({rel:.2})"
        );
    }

    #[test]
    fn turbulent_path_screens_flow_through_medium_trait() {
        let grid = Grid::new(32, 1e-3);
        let path = TurbulentPath::new(grid, 1e-6, 1e-14, 100.0, 500.0, 4, 9, 0);
        assert_eq!(path.n_screens(), 4);
        let dn = path.index_perturbation(2);
        assert_eq!(dn.dim(), (32, 32));
        // δn·k·dz must reproduce the stored screen phase scale: δn is tiny.
        assert!(dn.iter().all(|v| v.abs() < 1e-3));
    }

    /// Substeps must not change the total phase a screen imposes: exactly one
    /// sub-slab carries the screen (scaled to its thinner dz), the rest are
    /// zero, and slab indices map to the right screen.
    #[test]
    fn substeps_preserve_screen_phase() {
        let (wavelength, dz_screen) = (1e-6, 50.0);
        let k = 2.0 * PI / wavelength;
        let screens = vec![
            Array2::from_elem((16, 16), 0.3),
            Array2::from_elem((16, 16), -0.7),
        ];
        let path = TurbulentPath::from_screens(screens.clone(), wavelength, dz_screen)
            .with_substeps(5);
        assert_eq!(path.n_screens(), 2);
        assert_eq!(path.n_slabs(), 10);
        assert!((path.dz() - 10.0).abs() < 1e-12);

        for (s, screen) in screens.iter().enumerate() {
            for sub in 0..5 {
                let dn = path.index_perturbation(s * 5 + sub);
                if sub == 2 {
                    // Central sub-slab: propagator phase k·δn·dz == screen φ.
                    let phase = dn.mapv(|d| d * k * path.dz());
                    let max_err = (&phase - screen)
                        .iter()
                        .fold(0.0_f64, |m, v| m.max(v.abs()));
                    assert!(max_err < 1e-12, "screen phase not preserved: {max_err}");
                } else {
                    assert!(dn.iter().all(|&v| v == 0.0), "sub-slab {sub} not empty");
                }
            }
        }
    }

    #[test]
    #[should_panic(expected = "beyond path")]
    fn out_of_range_slab_panics() {
        let grid = Grid::new(16, 1e-3);
        let path = TurbulentPath::new(grid, 1e-6, 1e-14, 100.0, 100.0, 2, 3, 0);
        let _ = path.index_perturbation(2);
    }
}
